[[pages]]
path = "home.py"
name = "HOME"
icon = "ğŸ "

[[pages]]
path = "about_us.py"
name = "About Us"
icon = "ğŸ "

[[pages]]
path = "contact_us.py"
name = "Contact Us"
icon = "ğŸ "

[[pages]]
path = "Recipe.py"
name = "Lets Him Cook"
icon = "ğŸ "

[[pages]]
path = "Make_menu.py"
name = "Make Your Own Menu"
icon = "ğŸ "